final demodatas = [
  {
    'id': '0',
    'imageurl' : 'assets/images/sajjad.jpg',
    'title': 'Send Money',
    'account': 'Khalifa',
    'Trans_id': 'AHR7QCTCL8',
    'icon' : '-',
    'amount':  5000.00,
  },
  {
    'id': '2',
    'imageurl' : 'assets/images/tuhin1.jpg',
    'title': 'Received Money',
    'account': 'Tuhin',
    'Trans_id': 'AHU6T3VNEG',
    'icon' : '+',
    'amount': 300.00,
  },
  {
    'id': '3',
    'imageurl' : 'assets/images/Aro.jpg',
    'title': 'Send Money',
    'account': 'Adrita',
    'Trans_id': 'AHGDY6USJI',
    'icon' : '-',
    'amount':  1200.00,
  },
  {
    'id': '4',
    'imageurl' : 'assets/images/profile.png',
    'title': 'Received Money',
    'account': '01835100119',
    'Trans_id': 'AHISK8DH3U',
    'icon' : '+',
    'amount': 1300.00,
  },
  {
    'id': '5',
    'imageurl' : 'assets/images/profile.png',
    'title': 'Mobile Recharge',
    'account': 'Mom',
    'Trans_id': 'AHJAKXM7US',
    'icon' : '-',
    'amount': 36.00,
  },{
    'id': '6',
    'imageurl' : 'assets/images/profile.png',
    'title': 'Received Money',
    'account': '0185234975',
    'Trans_id': 'AHRJSOLE7W',
    'icon' : '+',
    'amount': 300.00,
  },
  {
    'id': '7',
    'imageurl' : 'assets/images/sajjad.jpg',
    'title': 'Send Money',
    'account': 'Khalifa',
    'Trans_id': 'AHR7LOPS0H',
    'icon' : '-',
    'amount':  1200.00,
  },
  {
    'id': '8',
    'imageurl' : 'assets/images/Aro.jpg',
    'title': 'Received Money',
    'account': '01835100119',
    'Trans_id': 'AHIERFSV7Y',
    'icon' : '+',
    'amount': 1300.00,
  },
  {
    'id': '9',
    'imageurl' : 'assets/images/profile.png',
    'title': 'Mobile Recharge',
    'account': 'Sajjad',
    'Trans_id': 'AHR7OBDGYE',
    'icon' : '-',
    'amount': 20.00,
  },{
    'id': '10',
    'imageurl' : 'assets/images/tuhin2.jpg',
    'title': 'Received Money',
    'account': 'Tuhin',
    'Trans_id': 'AHR7QKLN3O',
    'icon' : '+',
    'amount': 300.00,
  },
  {
    'id': '11',
    'imageurl' : 'assets/images/fahim.jpg',
    'title': 'Send Money',
    'account': 'Fahim',
    'Trans_id': 'AHR7QMLP09',
    'icon' : '-',
    'amount':  1200.00,
  },
  {
    'id': '12',
    'imageurl' : 'assets/images/profile.png',
    'title': 'Received Money',
    'account': '01835100119',
    'Trans_id': 'AHR7QCTCL8',
    'icon' : '+',
    'amount': 1300.00,
  },
  {
    'id': '13',
    'imageurl' : 'assets/images/Tawsif.jpg',
    'title': 'Mobile Recharge',
    'account': 'Tawsif',
    'Trans_id': 'AHR7QCTCL8',
    'icon' : '-',
    'amount': 50.00,
  },
];
final notifictions = [
  {

    'imageurl' : 'assets/images/notif1.jpg',
    'title': 'ঠিক সময়ে টাকা পাঠাতে ভুলে গেছেন?',
    'sub_title': 'সময়মতো সেন্ড মানি করতে সিলেক্ট করুন অটো পে!',
  },  {

    'imageurl' : 'assets/images/notif2.jpg',
    'title': 'আপনার জন্য আ্যড মানি-তে ৳৭৫ ক্যাশব্যাক',
    'sub_title': 'ব্যাংক অথবা কার্ড থেকে বিকাশ-এ ৳৭৫০০ আ্যডমানি-তে ৳৭৫ ক্যাশব্যাক',
  },
  {

    'imageurl' : 'assets/images/notif3.jpg',
    'title': '৭ কোটি মানুষের হাতে বিকাশ, সাথে বিকাশ',
    'sub_title': 'আজ সারাদেশের প্রতিটি মানুষ এগিয়ে যাচ্ছে একসাথে,বিকাশ-কে সাথে নিয়ে।',
  },
  {

    'imageurl' : 'assets/images/notif3.jpg',
    'title': '৭ কোটি মানুষের হাতে বিকাশ, সাথে বিকাশ',
    'sub_title': 'আজ সারাদেশের প্রতিটি মানুষ এগিয়ে যাচ্ছে একসাথে,বিকাশ-কে সাথে নিয়ে।',
  },


];
